project_id = "cbcxpfxdwymrsmncwznm"

[functions.process-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-featured-payment]
verify_jwt = false

[functions.verify-featured-payment]
verify_jwt = false
